version: '3'
services:
  mysql:
    build: mysql
    ports:
        - "13306:3306" # [外部向けポート:内部ポート]
    environment:
        - MYSQL_ROOT_PASSWORD=admpass
        - MYSQL_DATABASE=defaultdb
        - MYSQL_USER=defaultuser
        - MYSQL_PASSWORD=defaultpass
    # MySQLのコンテナ内のDBデータ(/var/lib/mysql)を、Dockerを動かしているホスト(./var/mysql/default)に保存 = データの永続化
    volumes:
        - db-volume:/var/lib/mysql # ホスト:コンテナ:アクセスモード(今回は省略)
        - log-volume:/var/log/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=admpass
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - session-volume:/sessions

volumes:
  db-volume:
  session-volume:
  log-volume: